### ISSUE TITLE
How to know if stove is turner on/off ?

### ISSUE THREAD

**Issue by tfossoul** [Chibald/maestrogateway#28]
Hi,

I'm currently trying to create a script to control my stove. 

How can we know if the stove is turned on/off ? The only way I see is to check the "Fume_Temperature" is upper than 50-70 degrees which is the only parameter that come often enough on the topic....

Do you have any other idea ?

**Comment by deSteini** [comment]
Hi @tfossoul,
the "Stove_State" should give you the information, in which state the stove is currently. If you save this, on every change, you should always have the current value. 
In case you are starting your Home Automatization while the stove is already running, and you require the data, you can always send the "Refresh" command ("mqttActions.publishMQTT( "SUBmcz", '{\"Command\": "Refresh", \"Value\": \"1\"}') ") to the script, which will return you all values of the stove again. I added a switch button to the app so that I can trigger the Refresh manually.
Hope that helped!
