### ISSUE TITLE
Docker Container leaks memory

### ISSUE THREAD

**Issue by tola2000** [Chibald/maestrogateway#38]
I'm running the latest build in a docker container and it builds up memory. 2 GB after less than a day.

**Comment by tola2000** [comment]
adding a ws.close() at the end of the while true loop might already do the trick.

**Comment by tola2000** [comment]
[_domotica-pelletkachel-1_logs (3).zip](https://github.com/Chibald/maestrogateway/files/7761825/_domotica-pelletkachel-1_logs.3.zip)

Logs...

**Comment by tola2000** [comment]
apparantly the threads created by     thread.start_new_thread(run, ()) don't get cleaned up. They remain in the stack.

**Comment by Chibald** [comment]
interesting subject.

It would seem like a lot of GB for only running couple of hours. 
I'm running it here on a RPI4 2GB ram alongside a couple (10+) of other containers. It's been running non-stop now since I published the last version, so thats 2 months without restart. Unfortunately my RPI doesn't reporting memory consumption for my containers so I can't verify the current memory consumption at this moment. But the pi has only got 2 GB....

So for me it's solid as a rock. I'm quite busy atm, so can't really look into it right now but if you find something keep me posted.  

In my experience a stable wifi connection to the stove is very important. If the wifi connection is not good enough you will encounter a lot of websocket connection failures and also failure to connect to the stove wifi eventually. Maybe the script will get into an unstable state if it runs into (too much) connection problems?

**Comment by tola2000** [comment]
I ran the gateway in the debugger on python 3.7 and than there is no issue. I suspect its a problem of the garbage collection not beeing triggered. I set the limit of the docker container to mem_limit: 100M to check if this will trigger garbage collect and free memory...

Wifi hasn't been the issue. I don't see any connection refused in the log...

`I'm quite busy atm`, no worries, I just log my experience and hopfully also a solution ;-)

**Comment by tola2000** [comment]
Currently it's running stable in the docker container. However I'm in doubt that the problem is related to that. But I'm not able to reproduce in the dev environment...

On change to consider:

```
def recuperoinfo_enqueue():
    """Get Stove information every x seconds as long as there is a websocket connection"""
    threading.Timer(get_stove_info_interval, recuperoinfo_enqueue).start()
    if websocket_connected:
        CommandQueue.put(MaestroCommandValue(MaestroCommand('GetInfo', 0, 'GetInfo', 'GetInfo'), 0))
        client.publish(_MQTT_TOPIC_PUB + 'state',  'ON',  1)  
```
You might want to switch the creation of the new timer trigger and the publish. If for any reason now the publish keeps sychrone and locked you create an enless amount of threads... I suggest to put the creation of the trigger at the end of the method...

**Comment by tola2000** [comment]
No issues anymore since I'm running on ClearLinux & Docker. No idea of the issue, but no longer able to reproduce...
