### ISSUE TITLE
Question about reliability / overall experience

### ISSUE THREAD

**Issue by domhaas** [Chibald/maestrogateway#40]
Hey there,

first of all: Thanks @Chibald for the work, much appreciated.

Background: We got finally installed our new [Pellet](https://www.mcz.it/de/produkte/pelletofen/ray/) today.
I was expecting that the official App is not that good, but anyhow, I thought it should do the job somehow. But I didn't expected that the App is really a great piece of sh*t.

Anyhow, I got a well configured OpenHab-Installation which should perfectly fit with this MQTT-Solution. Thanks again for that.
My question is: Are you (everybody here) using this Gateway in production, I mean as a full replacement for the "App" and is the Communication with the Pellet reliable at all? For sure, I need to configure my OpenHab for that to have a frontend, but that should be really no problem at all.
So, what I mean is: when I publish a message, like "stop the oven" does it work on the first try?

Thank you in advance & great new year.

Cheers,
Dominik

**Comment by Chibald** [comment]
Hi,

If you have a maestro v1, you can use this mqtt script combined with OpenHab as a full replacement of the original app. This is how I use it myself. In my house OpenHab is telling the stove to turn on of off based on some thermostat rules. I use it now for 2 years in "production".  I even blocked the stove for accessing the internet because of the overall crappiness and potential danger of having a stove connected via unencrypted (!) connection to an italian mcz server... So I don't use the original app at all.

But having a good connection between the stove and the device that runs the script is key. If this connection is not good, you will encounter a lot of connection loss on the websocket and crappy performance all over. The same as with the original app i guess ;) 

In an event of a short connection loss, the script will "remember" it has to deliver this message (it resides in a message queue) and it will deliver the message when connection is restored.

Good luck tweaking your stove and have a great new year!!

Cheers!

**Comment by domhaas** [comment]
> Hi,
> 
> If you have a maestro v1, you can use this mqtt script combined with OpenHab as a full replacement of the original app. This is how I use it myself. In my house OpenHab is telling the stove to turn on of off based on some thermostat rules. I use it now for 2 years in "production". I even blocked the stove for accessing the internet because of the overall crappiness and potential danger of having a stove connected via unencrypted (!) connection to an italian mcz server... So I don't use the original app at all.
> 
> But having a good connection between the stove and the device that runs the script is key. If this connection is not good, you will encounter a lot of connection loss on the websocket and crappy performance all over. The same as with the original app i guess ;)
> 
> In an event of a short connection loss, the script will "remember" it has to deliver this message (it resides in a message queue) and it will deliver the message when connection is restored.
> 
> Good luck tweaking your stove and have a great new year!!
> 
> Cheers!

Thanks for the quick reply.
And good point to firewall outgoing connections. Going to try it in the next weeks (being on vacation) and happy to give some feedback then.

Thanks again & wish you all the best.

Cheers,
Dominik

**Comment by domhaas** [comment]
Hey everyone,

I've found some time to manage everything working and it really works as expected with no issues at all. Thanks again @Chibald for your work.

Using this configuration:

- [MCZ Ray (Up)](https://www.mcz.it/de/produkte/pelletofen/ray/)
- pi4
- mosquitto mqtt
- openhab3
- openwrt-AP (connects to the client-network)
- edgerouter (static route to the client-network)

When everything is perfectly configured, hoping to find some time to contribute to the documentation and also there is for example the pelet-sensor, which needs to be bought extra is missing - going to check it out.

Cheers,
Dominik
