### ISSUE TITLE
Pellet_Sensor

### ISSUE THREAD

**Issue by NadeoGolf** [Chibald/maestrogateway#43]
Hello,

When i turn on the Pellet_Sensor, i can see a change on the "Maestro/Celcius_Or_Fahrenheit" topic in my logs.
Is it normal?

How return the state of the Pellet_Sensor?

**Comment by sfriedriszik** [comment]
Hello,
I would also be interested in the status of the pellet sensor.

**Comment by Chibald** [comment]
Hi, 

So maybe there is a mistake in the mapping of class MaestroInformation-frame for the status of the pellet sensor?
Currently frame 49 is mapped for celcius/fahrenheit setting. This could be incorrect.

I myself don't have a pellet sensor. What happens when the pellets run low?
Is there a signal on your MQTT stream that you seen incoming?

If there is a usefull frame maybe I will get a sensor myself :)

**Comment by Chibald** [comment]
OK, so I've done some snooping around and indeed the "Maestro/Celcius_Or_Fahrenheit" is, by mistake, connected to the pelletsensor values.
If your stove is supplied with a pellet sensor, and you enable it, you'll get the following values:

Maestro/Celcius_Or_Fahrenheit = 10 -> Full 
Maestro/Celcius_Or_Fahrenheit = 11 -> Empty

If I find the time I'll fix the script so the mqtt topic will make sense. But you can yuse it this way anyhow.


[maestro pellet sensor bug.txt](https://github.com/Chibald/maestrogateway/files/9485659/maestro.pellet.sensor.bug.txt)

**Comment by NadeoGolf** [comment]
Thank you for your reply, I don't have a pellet sensor but I plan to buy one. I wanted to see if it was supported before.

It would be really great if you updated the script to make this correct. :)
