### ISSUE TITLE
MCZ wifi access point vs integration into house wifi connected to the internet

### ISSUE THREAD

**Issue by waal10** [Chibald/maestrogateway#8]
Hi -
is it mandatory to run the MCZ as wifi access point and bridge the connection to my official house wifi?
Or is it also possible to integrate the MCZ into my house wifi connected to the internet?

Thanks ...

**Comment by Chibald** [comment]
Maybe it can work, but i'm not sure.

But this is what I know:
The stove can also connect to your local WIFI because that is the way the official app works.
You  stove will connect to some server in italy. The official app connects to that server and using the serial number of the stove the server in italy acts as a proxy for relaying the websocket communication to the stove.

you could try to connect to the stove on the dhcp ip address your stove gets on your wifi. Just set it up in the config file. I don't know if it will accept websocket connection on this interface.  let me know if it works, it would make connecting a lot easier :)

**Comment by knielen** [comment]
It does not work, Websocket connection error 111 (connection refused). To bad, would be great if this is possible.
